
var xa;xa||(xa=typeof Module !== 'undefined' ? Module : {});
(function(){function z(b){this.canvas=b;this.la=b.getContext("2d");this.fa=this.na=this.ja=null;this.ea=!1;this.ma()}function A(){this.ga=null;this.ea=W(2);this.stop=!1;this.da=k.de265_new_decoder();this.fa="undefined"!==typeof Worker&&"undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof Blob?new ea:new fa}function fa(){}function ea(){this.ha=[];if(null===ha){var b=ya.toString(),c=ya.name;c||(c=/^function\s+([\w\$]+)\s*\(/.exec(b)[1]);ha=window.URL.createObjectURL(new Blob(["(function() {\n",
za.toString()+";\n",ia.toString()+";\n",b+";\n",c+"();\n","}).call(this);"],{type:"text/javascript"}))}var d=this;this.worker=new Worker(ha);this.worker.addEventListener("message",function(e){switch(e.data.cmd){case "converted":var f=d.ha[0];d.ha=d.ha.splice(1);f(e.data.data.image);break;case "stopped":d=d.ha=null}},!1);this.worker.postMessage({cmd:"start"})}function P(b,c){this.ea=b;this.da=c;this.height=this.width=null}function Qa(b){return a.locateFile?a.locateFile(b,C):C+b}function Aa(b,c,d){d=
d||"i8";"*"===d.charAt(d.length-1)&&(d="i32");switch(d){case "i1":G[b>>0]=c;break;case "i8":G[b>>0]=c;break;case "i16":ja[b>>1]=c;break;case "i32":y[b>>2]=c;break;case "i64":ka=[c>>>0,(Q=c,1<=+Ra(Q)?0<Q?(Sa(+Ta(Q/4294967296),4294967295)|0)>>>0:~~+Ua((Q-+(~~Q>>>0))/4294967296)>>>0:0)];y[b>>2]=ka[0];y[b+4>>2]=ka[1];break;case "float":la[b>>2]=c;break;case "double":ma[b>>3]=c;break;default:H("invalid type for setValue: "+d)}}function I(b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":return G[b>>
0];case "i8":return G[b>>0];case "i16":return ja[b>>1];case "i32":return y[b>>2];case "i64":return y[b>>2];case "float":return la[b>>2];case "double":return ma[b>>3];default:H("invalid type for getValue: "+c)}return null}function na(b,c){b||H("Assertion failed: "+c)}function Ba(b){var c=a["_"+b];na(c,"Cannot call unknown function "+b+", make sure it is exported");return c}function Va(b,c,d,e){var f={string:function(l){var n=0;if(null!==l&&void 0!==l&&0!==l){var m=(l.length<<2)+1;n=oa(m);var u=w,t=
n;if(0<m){m=t+m-1;for(var x=0;x<l.length;++x){var v=l.charCodeAt(x);if(55296<=v&&57343>=v){var J=l.charCodeAt(++x);v=65536+((v&1023)<<10)|J&1023}if(127>=v){if(t>=m)break;u[t++]=v}else{if(2047>=v){if(t+1>=m)break;u[t++]=192|v>>6}else{if(65535>=v){if(t+2>=m)break;u[t++]=224|v>>12}else{if(t+3>=m)break;u[t++]=240|v>>18;u[t++]=128|v>>12&63}u[t++]=128|v>>6&63}u[t++]=128|v&63}}u[t]=0}}return n},array:function(l){var n=oa(l.length);G.set(l,n);return n}},g=Ba(b),h=[];b=0;if(e)for(var p=0;p<e.length;p++){var r=
f[d[p]];r?(0===b&&(b=Ca()),h[p]=r(e[p])):h[p]=e[p]}d=g.apply(null,h);d=function(l){return"string"===c?l?R(w,l,void 0):"":"boolean"===c?!!l:l}(d);0!==b&&Da(b);return d}function q(b,c,d,e){d=d||[];var f=d.every(function(g){return"number"===g});return"string"!==c&&f&&!e?Ba(b):function(){return Va(b,c,d,arguments,e)}}function R(b,c,d){var e=c+d;for(d=c;b[d]&&!(d>=e);)++d;if(16<d-c&&b.subarray&&Ea)return Ea.decode(b.subarray(c,d));for(e="";c<d;){var f=b[c++];if(f&128){var g=b[c++]&63;if(192==(f&224))e+=
String.fromCharCode((f&31)<<6|g);else{var h=b[c++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|b[c++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function Wa(b,c){0<b%c&&(b+=c-b%c);return b}function Fa(b){X=b;a.HEAP8=G=new Int8Array(b);a.HEAP16=ja=new Int16Array(b);a.HEAP32=y=new Int32Array(b);a.HEAPU8=w=new Uint8Array(b);a.HEAPU16=new Uint16Array(b);a.HEAPU32=new Uint32Array(b);a.HEAPF32=la=
new Float32Array(b);a.HEAPF64=ma=new Float64Array(b)}function Y(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var d=c.ua;"number"===typeof d?void 0===c.ka?a.dynCall_v(d):a.dynCall_vi(d,c.ka):d(void 0===c.ka?null:c.ka)}}}function H(b){if(a.onAbort)a.onAbort(b);Ga(b);L(b);Ha=!0;throw new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function pa(b,c){return String.prototype.startsWith?b.startsWith(c):0===b.indexOf(c)}function Ia(b){return pa(b,
"data:application/octet-stream;base64,")}function Ja(){try{if(S)return new Uint8Array(S);if(Z)return Z(D);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}function Xa(){return S||!aa&&!M||"function"!==typeof fetch||pa(D,"file://")?new Promise(function(b){b(Ja())}):fetch(D,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+D+"'";return b.arrayBuffer()}).catch(function(){return Ja()})}function T(){if(!T.da){var b={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:qa||"./this.program"},c;for(c in Ka)b[c]=Ka[c];var d=[];for(c in b)d.push(c+"="+b[c]);T.da=d}return T.da}function ra(){function b(){if(!ba&&(ba=!0,a.calledRun=!0,!Ha)){Y(La);Y(Ya);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;)Ma.unshift(a.postRun.shift());
Y(Ma)}}if(!(0<N)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Na.unshift(a.preRun.shift());Y(Na);0<N||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}function ya(){self.addEventListener("message",function(b){b=b.data;switch(b.cmd){case "stop":this.postMessage({cmd:"stopped"});self.close();break;case "convert":b=ia(b.data.chroma,b.data.y,b.data.u,b.data.v,b.data.w,b.data.h,b.data.stridey,
b.data.strideu,b.data.stridev,b.data.bppy,b.data.bppu,b.data.bppv),this.postMessage({cmd:"converted",data:{image:b}})}},0)}function za(b,c,d,e,f,g,h,p,r,l,n,m){l=r=0;e>>=1;for(var u=e*f,t=0,x=0,v=0,J,B,K=0;K<u;K++){B=K<<1;J=r<<1;f=1.164*(b[t+J]-16);n=c[x+r]-128;var ca=d[v+r]-128;m[B<<2]=f+1.596*ca;m[(B<<2)+1]=f-.813*ca-.391*n;m[(B<<2)+2]=f+2.018*n;m[(B<<2)+3]=255;f=1.164*(b[t+J+1]-16);m[B+1<<2]=f+1.596*ca;m[(B+1<<2)+1]=f-.813*ca-.391*n;m[(B+1<<2)+2]=f+2.018*n;m[(B+1<<2)+3]=255;r++;r===e&&(r=0,l++,
t+=g,x=(l>>1)*h,v=(l>>1)*p)}}function ia(b,c,d,e,f,g,h,p,r,l,n,m,u){u||(u=new Uint8ClampedArray(f*g*4));switch(b){case 0:console.log("Chroma format not implemented yet",b,l,n,m);break;case 1:8!==l||8!==n||8!==m?console.log("Chroma format not implemented yet",b,l,n,m):za(c,d,e,f,g,h,p,r,l,n,m,u);break;case 2:console.log("Chroma format not implemented yet",b,l,n,m);break;case 3:console.log("Chroma format not implemented yet",b,l,n,m);break;default:console.log("Unsupported chroma format",b,l,n,m)}return u}
var a={print:function(b){b=Array.prototype.slice.call(arguments).join(" ");console.log(b)},printErr:function(b){b=Array.prototype.slice.call(arguments).join(" ");console.error(b)},canvas:{},Ba:!0},E={};for(F in a)a.hasOwnProperty(F)&&(E[F]=a[F]);var qa="./this.program",aa=!1,M=!1,sa=!1,Oa=!1;aa="object"===typeof window;M="function"===typeof importScripts;sa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;Oa=!aa&&!sa&&!M;var C="",ta,ua;if(sa){C=
M?require("path").dirname(C)+"/":__dirname+"/";var va=function(b,c){ta||(ta=require("fs"));ua||(ua=require("path"));b=ua.normalize(b);return ta.readFileSync(b,c?null:"utf8")};var Z=function(b){b=va(b,!0);b.buffer||(b=new Uint8Array(b));na(b.buffer);return b};1<process.argv.length&&(qa=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){throw b;});process.on("unhandledRejection",H);a.inspect=function(){return"[Emscripten Module object]"}}else if(Oa)"undefined"!=
typeof read&&(va=function(b){return read(b)}),Z=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");na("object"===typeof b);return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(aa||M)M?C=self.location.href:document.currentScript&&(C=document.currentScript.src),C=0!==C.indexOf("blob:")?C.substr(0,C.lastIndexOf("/")+1):"",va=
function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},M&&(Z=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});var Ga=a.print||console.log.bind(console),L=a.printErr||console.warn.bind(console);for(F in E)E.hasOwnProperty(F)&&(a[F]=E[F]);E=null;a.thisProgram&&(qa=a.thisProgram);var S;a.wasmBinary&&(S=a.wasmBinary);"object"!==typeof WebAssembly&&L("no native wasm support detected");
var O;E=new WebAssembly.Table({initial:145,maximum:145,element:"anyfunc"});var Ha=!1,Ea="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,G,w,ja,y,la,ma;var F=a.INITIAL_MEMORY||16777216;a.wasmMemory?O=a.wasmMemory:O=new WebAssembly.Memory({initial:F/65536,maximum:32768});if(O)var X=O.buffer;F=X.byteLength;Fa(X);y[10708]=5285872;var Na=[],La=[],Ya=[],Ma=[],Ra=Math.abs,Ua=Math.ceil,Ta=Math.floor,Sa=Math.min,N=0,wa=null,U=null;a.preloadedImages={};a.preloadedAudios={};var D="libde265.wasm";
Ia(D)||(D=Qa(D));var Q,ka;La.push({ua:function(){Pa()}});var Ka={},V={Aa:{},sa:[null,[],[]],xa:function(b,c){var d=V.sa[b];0===c||10===c?((1===b?Ga:L)(R(d,0)),d.length=0):d.push(c)},oa:void 0,get:function(){V.oa+=4;return y[V.oa-4>>2]},za:function(b){return b?R(w,b,void 0):""},ya:function(b){return b}},Za={a:function(b,c,d,e){H("Assertion failed: "+(b?R(w,b,void 0):"")+", at: "+[c?c?R(w,c,void 0):"":"unknown filename",d,e?e?R(w,e,void 0):"":"unknown function"])},b:function(){H()},k:function(b,c,d){w.copyWithin(b,
c,c+d)},l:function(b){var c=w.length;if(2147483648<b)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,b+100663296);e=Math.min(2147483648,Wa(Math.max(16777216,b,e),65536));a:{try{O.grow(e-X.byteLength+65535>>>16);Fa(O.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},e:function(b,c){var d=0;T().forEach(function(e,f){var g=c+d;f=y[b+4*f>>2]=g;for(g=0;g<e.length;++g)G[f++>>0]=e.charCodeAt(g);G[f>>0]=0;d+=e.length+1});return 0},f:function(b,c){var d=T();y[b>>2]=d.length;
var e=0;d.forEach(function(f){e+=f.length+1});y[c>>2]=e;return 0},h:function(){return 0},i:function(){},c:function(b,c,d,e){for(var f=0,g=0;g<d;g++){for(var h=y[c+8*g>>2],p=y[c+(8*g+4)>>2],r=0;r<p;r++)V.xa(b,w[h+r]);f+=p}y[e>>2]=f;return 0},memory:O,d:function(){return 6},g:function(){},j:function(){},table:E};E=function(){function b(f){a.asm=f.exports;N--;a.monitorRunDependencies&&a.monitorRunDependencies(N);0==N&&(null!==wa&&(clearInterval(wa),wa=null),U&&(f=U,U=null,f()))}function c(f){b(f.instance)}
function d(f){return Xa().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){L("failed to asynchronously prepare wasm: "+g);H(g)})}var e={a:Za};N++;a.monitorRunDependencies&&a.monitorRunDependencies(N);if(a.instantiateWasm)try{return a.instantiateWasm(e,b)}catch(f){return L("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(S||"function"!==typeof WebAssembly.instantiateStreaming||Ia(D)||pa(D,"file://")||"function"!==typeof fetch)return d(c);fetch(D,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
e).then(c,function(g){L("wasm streaming compile failed: "+g);L("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}();a.asm=E;var Pa=a.___wasm_call_ctors=function(){return(Pa=a.___wasm_call_ctors=a.asm.m).apply(null,arguments)};a._de265_get_version=function(){return(a._de265_get_version=a.asm.n).apply(null,arguments)};a._de265_get_version_number=function(){return(a._de265_get_version_number=a.asm.o).apply(null,arguments)};a._de265_get_error_text=function(){return(a._de265_get_error_text=
a.asm.p).apply(null,arguments)};a._de265_isOK=function(){return(a._de265_isOK=a.asm.q).apply(null,arguments)};a._de265_new_decoder=function(){return(a._de265_new_decoder=a.asm.r).apply(null,arguments)};a._de265_free_decoder=function(){return(a._de265_free_decoder=a.asm.s).apply(null,arguments)};a._de265_push_data=function(){return(a._de265_push_data=a.asm.t).apply(null,arguments)};a._de265_flush_data=function(){return(a._de265_flush_data=a.asm.u).apply(null,arguments)};a._de265_decode=function(){return(a._de265_decode=
a.asm.v).apply(null,arguments)};a._de265_push_NAL=function(){return(a._de265_push_NAL=a.asm.w).apply(null,arguments)};a._de265_push_end_of_NAL=function(){return(a._de265_push_end_of_NAL=a.asm.x).apply(null,arguments)};a._de265_push_end_of_frame=function(){return(a._de265_push_end_of_frame=a.asm.y).apply(null,arguments)};a._de265_reset=function(){return(a._de265_reset=a.asm.z).apply(null,arguments)};a._de265_get_next_picture=function(){return(a._de265_get_next_picture=a.asm.A).apply(null,arguments)};
a._de265_peek_next_picture=function(){return(a._de265_peek_next_picture=a.asm.B).apply(null,arguments)};a._de265_release_next_picture=function(){return(a._de265_release_next_picture=a.asm.C).apply(null,arguments)};a._de265_get_highest_TID=function(){return(a._de265_get_highest_TID=a.asm.D).apply(null,arguments)};a._de265_get_current_TID=function(){return(a._de265_get_current_TID=a.asm.E).apply(null,arguments)};a._de265_set_limit_TID=function(){return(a._de265_set_limit_TID=a.asm.F).apply(null,arguments)};
a._de265_set_framerate_ratio=function(){return(a._de265_set_framerate_ratio=a.asm.G).apply(null,arguments)};a._de265_change_framerate=function(){return(a._de265_change_framerate=a.asm.H).apply(null,arguments)};a._de265_get_warning=function(){return(a._de265_get_warning=a.asm.I).apply(null,arguments)};a._de265_set_parameter_bool=function(){return(a._de265_set_parameter_bool=a.asm.J).apply(null,arguments)};a._de265_set_parameter_int=function(){return(a._de265_set_parameter_int=a.asm.K).apply(null,arguments)};
a._de265_get_parameter_bool=function(){return(a._de265_get_parameter_bool=a.asm.L).apply(null,arguments)};a._de265_get_number_of_input_bytes_pending=function(){return(a._de265_get_number_of_input_bytes_pending=a.asm.M).apply(null,arguments)};a._de265_get_number_of_NAL_units_pending=function(){return(a._de265_get_number_of_NAL_units_pending=a.asm.N).apply(null,arguments)};a._de265_get_image_width=function(){return(a._de265_get_image_width=a.asm.O).apply(null,arguments)};a._de265_get_image_height=function(){return(a._de265_get_image_height=
a.asm.P).apply(null,arguments)};a._de265_get_bits_per_pixel=function(){return(a._de265_get_bits_per_pixel=a.asm.Q).apply(null,arguments)};a._de265_get_chroma_format=function(){return(a._de265_get_chroma_format=a.asm.R).apply(null,arguments)};a._de265_get_image_plane=function(){return(a._de265_get_image_plane=a.asm.S).apply(null,arguments)};a._de265_get_image_plane_user_data=function(){return(a._de265_get_image_plane_user_data=a.asm.T).apply(null,arguments)};a._de265_get_image_PTS=function(){return(a._de265_get_image_PTS=
a.asm.U).apply(null,arguments)};a._de265_get_image_user_data=function(){return(a._de265_get_image_user_data=a.asm.V).apply(null,arguments)};a._de265_set_image_user_data=function(){return(a._de265_set_image_user_data=a.asm.W).apply(null,arguments)};a._de265_set_verbosity=function(){return(a._de265_set_verbosity=a.asm.X).apply(null,arguments)};var W=a._malloc=function(){return(W=a._malloc=a.asm.Y).apply(null,arguments)},da=a._free=function(){return(da=a._free=a.asm.Z).apply(null,arguments)},Ca=a.stackSave=
function(){return(Ca=a.stackSave=a.asm._).apply(null,arguments)},oa=a.stackAlloc=function(){return(oa=a.stackAlloc=a.asm.$).apply(null,arguments)},Da=a.stackRestore=function(){return(Da=a.stackRestore=a.asm.aa).apply(null,arguments)};a.dynCall_vi=function(){return(a.dynCall_vi=a.asm.ba).apply(null,arguments)};a.dynCall_v=function(){return(a.dynCall_v=a.asm.ca).apply(null,arguments)};a.asm=E;var ba;U=function c(){ba||ra();ba||(U=c)};a.run=ra;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=
[a.preInit]);0<a.preInit.length;)a.preInit.pop()();ra();delete this.Module;var k={DE265_OK:0,DE265_ERROR_NO_SUCH_FILE:1,DE265_ERROR_EOF:3,DE265_ERROR_COEFFICIENT_OUT_OF_IMAGE_BOUNDS:4,DE265_ERROR_CHECKSUM_MISMATCH:5,DE265_ERROR_CTB_OUTSIDE_IMAGE_AREA:6,DE265_ERROR_OUT_OF_MEMORY:7,DE265_ERROR_CODED_PARAMETER_OUT_OF_RANGE:8,DE265_ERROR_IMAGE_BUFFER_FULL:9,DE265_ERROR_CANNOT_START_THREADPOOL:10,DE265_ERROR_LIBRARY_INITIALIZATION_FAILED:11,DE265_ERROR_LIBRARY_NOT_INITIALIZED:12,DE265_ERROR_WAITING_FOR_INPUT_DATA:13,
DE265_ERROR_CANNOT_PROCESS_SEI:14,DE265_ERROR_PARAMETER_PARSING:15,DE265_ERROR_NO_INITIAL_SLICE_HEADER:16,DE265_ERROR_PREMATURE_END_OF_SLICE:17,DE265_ERROR_UNSPECIFIED_DECODING_ERROR:18,DE265_ERROR_MAX_THREAD_CONTEXTS_EXCEEDED:500,DE265_ERROR_MAX_NUMBER_OF_SLICES_EXCEEDED:501,DE265_ERROR_NOT_IMPLEMENTED_YET:502,DE265_WARNING_NO_WPP_CANNOT_USE_MULTITHREADING:1E3,DE265_WARNING_WARNING_BUFFER_FULL:1001,DE265_WARNING_PREMATURE_END_OF_SLICE_SEGMENT:1002,DE265_WARNING_INCORRECT_ENTRY_POINT_OFFSET:1003,
DE265_WARNING_CTB_OUTSIDE_IMAGE_AREA:1004,DE265_WARNING_SPS_HEADER_INVALID:1005,DE265_WARNING_PPS_HEADER_INVALID:1006,DE265_WARNING_SLICEHEADER_INVALID:1007,DE265_WARNING_INCORRECT_MOTION_VECTOR_SCALING:1008,DE265_WARNING_NONEXISTING_PPS_REFERENCED:1009,DE265_WARNING_NONEXISTING_SPS_REFERENCED:1010,DE265_WARNING_BOTH_PREDFLAGS_ZERO:1011,DE265_WARNING_NONEXISTING_REFERENCE_PICTURE_ACCESSED:1012,DE265_WARNING_NUMMVP_NOT_EQUAL_TO_NUMMVQ:1013,DE265_WARNING_NUMBER_OF_SHORT_TERM_REF_PIC_SETS_OUT_OF_RANGE:1014,
DE265_WARNING_SHORT_TERM_REF_PIC_SET_OUT_OF_RANGE:1015,DE265_WARNING_FAULTY_REFERENCE_PICTURE_LIST:1016,DE265_WARNING_EOSS_BIT_NOT_SET:1017,DE265_WARNING_MAX_NUM_REF_PICS_EXCEEDED:1018,DE265_WARNING_INVALID_CHROMA_FORMAT:1019,DE265_WARNING_SLICE_SEGMENT_ADDRESS_INVALID:1020,DE265_WARNING_DEPENDENT_SLICE_WITH_ADDRESS_ZERO:1021,DE265_WARNING_NUMBER_OF_THREADS_LIMITED_TO_MAXIMUM:1022,DE265_NON_EXISTING_LT_REFERENCE_CANDIDATE_IN_SLICE_HEADER:1023,DE265_WARNING_CANNOT_APPLY_SAO_OUT_OF_MEMORY:1024,DE265_WARNING_SPS_MISSING_CANNOT_DECODE_SEI:1025,
DE265_WARNING_COLLOCATED_MOTION_VECTOR_OUTSIDE_IMAGE_AREA:1026,de265_get_version:q("de265_get_version","string"),de265_get_version_number:q("de265_get_version_number","number"),de265_get_error_text:q("de265_get_error_text","string",["number"]),de265_isOK:q("de265_isOK","number",["number"]),de265_set_verbosity:q("de265_set_verbosity","number",["number"]),de265_chroma_mono:0,de265_chroma_420:1,de265_chroma_422:2,de265_chroma_444:3,de265_get_image_width:q("de265_get_image_width","number",["number","number"]),
de265_get_image_height:q("de265_get_image_height","number",["number","number"]),de265_get_chroma_format:q("de265_get_chroma_format","number",["number"]),de265_get_bits_per_pixel:q("de265_get_bits_per_pixel","number",["number","number"]),de265_get_image_plane:q("de265_get_image_plane","number",["number","number","number"]),de265_get_image_plane_user_data:q("de265_get_image_plane_user_data","number",["number","number"]),de265_get_image_PTS:q("de265_get_image_PTS","number",["number"]),de265_get_image_user_data:q("de265_get_image_user_data",
"number",["number"]),de265_set_image_user_data:q("de265_set_image_user_data","number",["number","number"]),de265_new_decoder:q("de265_new_decoder","number"),de265_free_decoder:q("de265_free_decoder","number",["number"]),de265_push_data:q("de265_push_data","number",["number","array","number","number","number"]),de265_push_end_of_NAL:q("de265_push_end_of_NAL","number",["number"]),de265_push_end_of_frame:q("de265_push_end_of_frame","number",["number"]),de265_push_NAL:q("de265_push_NAL","number",["number",
"array","number","number","number"]),de265_flush_data:q("de265_flush_data","number",["number"]),de265_get_number_of_input_bytes_pending:q("de265_get_number_of_input_bytes_pending","number",["number"]),de265_get_number_of_NAL_units_pending:q("de265_get_number_of_NAL_units_pending","number",["number"]),de265_decode:q("de265_decode","number",["number","number"]),de265_reset:q("de265_reset","number",["number"]),de265_peek_next_picture:q("de265_peek_next_picture","number",["number"]),de265_get_next_picture:q("de265_get_next_picture",
"number",["number"]),de265_release_next_picture:q("de265_release_next_picture","number",["number"]),de265_get_warning:q("de265_get_warning","number",["number"]),de265_get_highest_TID:q("de265_get_highest_TID","number",["number"]),de265_get_current_TID:q("de265_get_current_TID","number",["number"]),de265_set_limit_TID:q("de265_set_limit_TID","number",["number","number"]),de265_set_framerate_ratio:q("de265_set_framerate_ratio","number",["number","number"]),de265_change_framerate:q("de265_change_framerate",
"number",["number","number"]),DE265_DECODER_PARAM_BOOL_SEI_CHECK_HASH:0,DE265_DECODER_PARAM_DUMP_SPS_HEADERS:1,DE265_DECODER_PARAM_DUMP_VPS_HEADERS:2,DE265_DECODER_PARAM_DUMP_PPS_HEADERS:3,DE265_DECODER_PARAM_DUMP_SLICE_HEADERS:4,DE265_DECODER_PARAM_ACCELERATION_CODE:5,DE265_DECODER_PARAM_SUPPRESS_FAULTY_PICTURES:6,DE265_DECODER_PARAM_DISABLE_DEBLOCKING:7,DE265_DECODER_PARAM_DISABLE_SAO:8,de265_acceleration_SCALAR:0,de265_acceleration_MMX:10,de265_acceleration_SSE:20,de265_acceleration_SSE2:30,de265_acceleration_SSE4:40,
de265_acceleration_AVX:50,de265_acceleration_AVX2:60,de265_acceleration_ARM:70,de265_acceleration_NEON:80,de265_acceleration_AUTO:1E4,de265_set_parameter_bool:q("de265_set_parameter_bool","number",["number","number","number"]),de265_set_parameter_int:q("de265_set_parameter_int","number",["number","number","number"]),de265_get_parameter_bool:q("de265_get_parameter_bool","number",["number","number"])};P.prototype.free=function(){};P.prototype.get_width=function(){null===this.width&&(this.width=k.de265_get_image_width(this.da,
0));return this.width};P.prototype.get_height=function(){null===this.height&&(this.height=k.de265_get_image_height(this.da,0));return this.height};P.prototype.get_yuv=function(){this.get_width();var c=this.get_height();k.de265_get_chroma_format(this.da);var d=W(4),e=k.de265_get_image_plane(this.da,0,d),f=I(d,"i32");k.de265_get_bits_per_pixel(this.da,0);var g=k.de265_get_image_plane(this.da,1,d),h=I(d,"i32");k.de265_get_bits_per_pixel(this.da,1);var p=k.de265_get_image_plane(this.da,2,d),r=I(d,"i32");
k.de265_get_bits_per_pixel(this.da,2);da(d);e=w.subarray(e,e+c*f);g=w.subarray(g,g+c/2*h);p=w.subarray(p,p+c/2*r);c=new Uint8Array(e.length+g.length+p.length);c.set(e);c.set(g,e.length);c.set(p,e.length+g.length);return c};P.prototype.display=function(c,d){var e=this.get_width(),f=this.get_height(),g=k.de265_get_chroma_format(this.da),h=W(4),p=k.de265_get_image_plane(this.da,0,h),r=I(h,"i32"),l=k.de265_get_bits_per_pixel(this.da,0),n=k.de265_get_image_plane(this.da,1,h),m=I(h,"i32"),u=k.de265_get_bits_per_pixel(this.da,
1),t=k.de265_get_image_plane(this.da,2,h),x=I(h,"i32"),v=k.de265_get_bits_per_pixel(this.da,2);da(h);this.ea.ta(g,p,n,t,e,f,r,m,x,l,u,v,c,d)};var ha=null;ea.prototype.destroy=function(){this.worker&&(this.worker.postMessage({cmd:"stop"}),this.worker=null)};ea.prototype.pa=function(c,d,e,f,g,h,p,r,l,n,m,u,t,x){c={cmd:"convert",data:{chroma:c,y:new Uint8Array(d),u:new Uint8Array(e),v:new Uint8Array(f),w:g,h:h,stridey:p,strideu:r,stridev:l,bppy:n,bppu:m,bppv:u}};this.ha.push(function(v){if(t.data.set)t.data.set(v);
else for(var J=t.data,B=J.length,K=0;K<B;K++)J[K]=v[K];x(t)});this.worker.postMessage(c)};fa.prototype.destroy=function(){};fa.prototype.pa=function(c,d,e,f,g,h,p,r,l,n,m,u,t,x){ia(c,d,e,f,g,h,p,r,l,n,m,u,t.data);x(t)};A.prototype.free=function(){this.fa&&(this.fa.destroy(),this.fa=null);k.de265_free_decoder(this.da);this.da=null;da(this.ea);this.ea=null};A.prototype.set_image_callback=function(c){this.ga=c};A.prototype.reset=function(){k.de265_reset(this.da)};A.prototype.push_data=function(c,d){return k.de265_push_data(this.da,
c,c.length,d||0,0)};A.prototype.flush=function(){this.stop=!0;return k.de265_flush_data(this.da)};A.prototype.has_more=function(){return!this.stop||0!==I(this.ea,"i16")};A.prototype.set_framerate_ratio=function(c){k.de265_set_framerate_ratio(this.da,c)};A.prototype.disable_filters=function(c){k.de265_set_parameter_bool(this.da,k.DE265_DECODER_PARAM_DISABLE_DEBLOCKING,!!c);k.de265_set_parameter_bool(this.da,k.DE265_DECODER_PARAM_DISABLE_SAO,!!c)};A.prototype.decode=function(c){for(Aa(this.ea,1,"i16");0!==
I(this.ea,"i16");){var d=k.de265_decode(this.da,this.ea);if(!k.de265_isOK(d)){Aa(this.ea,0,"i16");break}var e=k.de265_get_next_picture(this.da);if(e){this.ga&&this.ga(new P(this,e));break}}c(d)};A.prototype.ta=function(c,d,e,f,g,h,p,r,l,n,m,u,t,x){d=w.subarray(d,d+h*p);e=w.subarray(e,e+h*r);f=w.subarray(f,f+h*l);this.fa.pa(c,d,e,f,g,h,p,r,l,n,m,u,t,x)};k.Decoder=A;z.prototype.ma=function(){this.start=null;this.frames=0;this.ga=null;this.ra=!1;this.ia=null};z.prototype.set_status_callback=function(c){this.ja=
c};z.prototype.da=function(){this.ja&&this.ja.apply(this.ja,arguments)};z.prototype.set_error_callback=function(c){this.na=c};z.prototype.qa=function(c,d){this.na&&this.na(c,d)};z.prototype.va=function(c){if(this.start){this.frames+=1;var d=new Date-this.start;1E3<d&&this.da("fps",this.frames/(.001*d))}else this.start=new Date,this.da("playing");d=c.get_width();var e=c.get_height();if(d!=this.canvas.width||e!=this.canvas.height||!this.ga){this.canvas.width=d;this.canvas.height=e;this.ga=this.la.createImageData(d,
e);for(var f=this.ga.data,g=0;g<d*e;g++)f[4*g+3]=255}var h=this;c.display(this.ga,function(p){window.requestAnimationFrame?(h.ia=p,window.requestAnimationFrame(function(){h.ia&&(h.la.putImageData(h.ia,0,0),h.ia=null)})):h.la.putImageData(p,0,0)})};z.prototype.wa=function(c){function d(){if(e.ra){if(0===p)var n=f.flush();else{var m=4096;m>p&&(m=p);n=new Uint8Array(g,h,m);n=f.push_data(n);h+=m;p-=m}k.de265_isOK(n)?(e.fa!==r&&(f.set_framerate_ratio(e.fa),r=e.fa),e.ea!==l&&(f.disable_filters(e.ea),l=
e.ea),f.decode(function(u){switch(u){case k.DE265_ERROR_WAITING_FOR_INPUT_DATA:setTimeout(d,0);return;default:if(!k.de265_isOK(u)){e.qa(u,k.de265_get_error_text(u));return}}0<p||f.has_more()?setTimeout(d,0):(f.free(),e.stop())})):e.qa(n,k.de265_get_error_text(n))}}var e=this;this.da("initializing");var f=new A;f.set_image_callback(function(n){e.va(n);n.free()});var g=c.response,h=0,p=g.byteLength,r=null,l=!1;setTimeout(d,0)};z.prototype.playback=function(c){this.ma();var d=new XMLHttpRequest;d.open("get",
c,!0);d.responseType="arraybuffer";var e=this;d.onload=function(){e.wa(d)};this.da("loading");this.ra=!0;d.send()};z.prototype.stop=function(){this.da("stopped");this.ma()};z.prototype.set_framerate_ratio=function(c){this.fa=c};z.prototype.disable_filters=function(c){this.ea=c};k.RawPlayer=z;"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=k),exports.libde265=k):this.libde265=k;"function"===typeof define&&define.da&&define([],function(){return k})}).call(this);